version: "3.8"

services:
  db:
    container_name: poc_db
    restart: always
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d poc_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      minio-buckets:
        condition: service_completed_successfully
    volumes:
      - ./app:/app/app
      - ./config:/app/config

  minio:
    image: minio/minio
    container_name: poc_minio
    restart: always
    environment:
      MINIO_ROOT_USER: "user"
      MINIO_ROOT_PASSWORD: "password"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 user password;
      mc mb myminio/media --ignore-existing;
      mc anonymous set download myminio/media;
      exit 0;
      "

volumes:
  app_pg_data:
  minio_data:
